V = 0
SOURCE_DIR = src
INCLUDE_DIR = include
BUILD_DIR = build

LIBDRAGON_PREVIEW = 2
include $(N64_INST)/include/n64.mk

SRCS = $(wildcard $(SOURCE_DIR)/*.c)
OBJS = $(SRCS:$(SOURCE_DIR)/%.c=$(BUILD_DIR)/%.o)

N64_C_AND_CXX_FLAGS += -I$(INCLUDE_DIR)

.PHONY: all
all: hicart.z64

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR) *.z64

hicart.z64: N64_ROM_TITLE="Home Invader 64"
hicart.z64: $(BUILD_DIR)/hicart.dfs

$(BUILD_DIR)/hicart.dfs: $(wildcard filesystem/*)
$(BUILD_DIR)/hicart.elf: $(OBJS)

-include $(wildcard $(BUILD_DIR)/*.d)
