[project]
name = "hicart"
version = "0.1.0"
description = ""
authors = [
    {name = "Nelson Gauthier", email = "nelson.gauthier@gmail.com"}
]

requires-python = "~=3.10.0"
dependencies = [
    "pyftdi~=0.53.3",
    "setuptools>=67.0",

    "amaranth @ git+https://github.com/amaranth-lang/amaranth.git@main",
    "amaranth-soc @ git+https://github.com/jfng/amaranth-soc.git@main",
    "amaranth-stdio @ git+https://github.com/amaranth-lang/amaranth-stdio.git@main",
    "amaranth-boards @ git+https://github.com/amaranth-lang/amaranth-boards.git@main",
    "minerva @ git+https://github.com/minerva-cpu/minerva.git@main",

    "yowasp-yosys~=0.69.0",
    "yowasp-nextpnr-ecp5~=0.11.1",
]

[tool.pdm.dev-dependencies]
test = [
    "pytest~=7.1.3"
]

[tool.pdm.resolution.overrides]
amaranth = "git+https://github.com/amaranth-lang/amaranth.git@v0.5.10"
amaranth-soc = "git+https://github.com/amaranth-lang/amaranth-soc.git@3e3d8b72"
amaranth-stdio = "git+https://github.com/amaranth-lang/amaranth-stdio.git@bb39058b"
amaranth-boards = "git+https://github.com/amaranth-lang/amaranth-boards.git@91ffa38e"
minerva = "git+https://github.com/minerva-cpu/minerva.git@6109879e"

[tool.pdm.scripts]
test = { cmd = "pytest" }

[tool.pdm.scripts._.env]
YOSYS = "yowasp-yosys"
NEXTPNR_ECP5 = "yowasp-nextpnr-ecp5"
ECPPACK = "yowasp-ecppack"

[tool.pyright]
venvPath = ".venv"
typeCheckingMode = "off"
reportWildcardImportFromLibrary = "none"
reportInvalidTypeForm = "none"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
